Catkin-ProjectName: ecto
Version: 0.1.1
Description: Ecto is a hybrid C++/Python development framework for constructing and maintaining pipelines.
Author: Ethan Rublee <erublee@willowgarage.com>, Troy Straszheim <straszheim@willowgarage.com>
Maintainer:  Ethan Rublee <erublee@willowgarage.com>
Homepage:  http://ecto.willowgarage.com

Depends: catkin, boost

Catkin-CopyrightType:  willowgarage
Catkin-ChangelogType: +catkin/changelog.em
Catkin-DebRulesType: +catkin/rules.em

Release-Pull: git://github.com/wg-debs/ecto.git
Release-Push: git@github.com:wg-debs/ecto.git

